### ISSUE TITLE
available tags

### ISSUE THREAD

**Issue by daturon** [mvader/react-categorized-tag-input#15]
Hello! How a user can see a set of available tags designed for quick selection without typing?

**Comment by daturon** [comment]
A user can type double space but maybe the user can get it other way?

**Comment by erizocosmico** [comment]
There is no way to do that right now but feel free to send a PR with that feature if you need it.

**Comment by daturon** [comment]
OK.

**Comment by daturon** [comment]
@mvader I get all available tags just typing double space;)

**Comment by ehartford** [comment]
bug should be open, until someone submits a PR, its quite valid.
