### ISSUE TITLE
error when placeholder attribute undefined

### ISSUE THREAD

**Issue by ksloan** [mvader/react-categorized-tag-input#17]
Hey, great work on this component -- _thanks_! Just wanted to let you know it's throwing this error for me if you don't provide a placeholder attribute:

`Uncaught TypeError: Cannot read property 'length' of undefined` when trying to read this.props.placeholder.length.

**Comment by erizocosmico** [comment]
Thanks for catching this! Just released version `2.1.2` with this fix.
