### ISSUE TITLE
Once I select an item from the list and hit tab that item continues to populate the search bar instead of leaving.

### ISSUE THREAD

**Issue by kthurimella** [mvader/react-categorized-tag-input#3]
If I'm on your demo here: http://mvader.me/react-categorized-tag-input/

and I type "Apes" the tag appears properly. However, when I continue hitting tab Apes continues to populate as new tags, which seems like a bug.

**Comment by kthurimella** [comment]
Same thing happens with enter and comma

**Comment by erizocosmico** [comment]
Yes, it is indeed a bug, I will to fix it and release the 1.1.1 version with this and the placeholder
