### ISSUE TITLE
warning.js:45 Warning: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by rkmax** [mvader/react-categorized-tag-input#5]
![captura de pantalla de 2016-03-23 00-50-22](https://cloud.githubusercontent.com/assets/395707/13976804/41fd1696-f091-11e5-9eac-3f1d12d2aba7.png)

I have a logic where show a static content or a editable content based on a switch

the switch it's pretty simple

```
{allowEdit ? <TagInput {...props} /> : <span>{...}</span>}
```

the problem arises when allowEdit is set to false and the TagInput is unmounted

**Comment by erizocosmico** [comment]
I'm going to setup a project and see if I can reproduce and fix this and get back to you ASAP, thanks for reporting.

**Comment by erizocosmico** [comment]
@rkmax fixed on `1.1.3`, there was a timeout with a reference to the component that was not being cleared on unmount

**Comment by rkmax** [comment]
thanks @mvader I'll check this new version
