### ISSUE TITLE
Enable tags to have distinct styles

### ISSUE THREAD

**Issue by mheiber** [mvader/react-categorized-tag-input#7]
I need to apply colors to specific tags (some red, some blue, for example).
Do you have a suggestion for the cleanest way to do this? I can do a PR.
Proposal:    an optional `getTagStyle` prop   that is a function from tagName to a style object, which is then applied to the `.cti__tag` div and its children.

**Comment by erizocosmico** [comment]
Yes, that would be a really cool idea! You're welcome to open a PR with that :)

**Comment by mheiber** [comment]
@mvader thanks for getting back to me. Here's the PR: https://github.com/mvader/react-categorized-tag-input/pull/8 . I updated the sample and the readme to show how to use it. Looking forward to your feedback!

**Comment by erizocosmico** [comment]
Thanks for the PR!
